package com.live.monitor.entity;

import java.util.List;
import java.util.Map;

public class MonitorService {
    public Long id;
    public String serviceName;
    public String serviceCategory;
    public String serviceType;
    public String clusterName;
    public String monitorReason;
    public String endpoint;
    public String host;
    public Integer port;
    public String checkMode;
    public String checkCommand;
    public String expectedResult;
    public Long hostId;
    public Double cpuThresholdPercent;
    public Double memoryThresholdPercent;
    public Double diskThresholdPercent;
    public Boolean cpuAlertEnabled;
    public Boolean memoryAlertEnabled;
    public Boolean diskAlertEnabled;
    public Boolean serviceAlertEnabled;
    public Integer serviceConsecutiveFailures;
    public Integer serviceRecoverSuccesses;
    public Integer serviceAlertCooldownSeconds;
    public String processName;
    public String processMatchKeyword;
    public String processMatchMode;
    public String processCheckCommand;
    public Integer processMinInstances;
    public String configJson;
    public String secretConfigJson;
    public String url;
    public String httpMethod;
    public Integer expectedStatusCode;
    public String responseKeyword;
    public String apiAssertionExpression;
    public List<Map<String, String>> apiHeaders;
    public String apiContentType;
    public String apiRequestBody;
    public String apiAuthType;
    public String apiBasicUsername;
    public String apiBasicPassword;
    public String apiBearerToken;
    public String apiAuthAppId;
    public String apiAuthAppSecret;
    public Integer apiResponseTimeMs;
    public String apiJsonAssertions;
    public String apiTextAssertionMode;
    public String apiTextAssertionValue;
    public Boolean ignoreSslVerification;
    public Double checkTimeoutSeconds;
    public String redisUsername;
    public String redisPassword;
    public Boolean redisClusterMode;
    public String zookeeperCheckMode;
    public String zookeeperCheckCommand;
    public Integer zookeeperExpectedNodes;
    public String databaseName;
    public String databaseUsername;
    public String databasePassword;
    public Long databaseConnectionServiceId;
    public String databaseQuery;
    public String databaseResultOperator;
    public List<String> databaseAssertionFields;
    public String jdbcDriverClass;
    public String jdbcUrl;
    public Integer checkInterval;
    public Integer checkIntervalValue;
    public String checkIntervalUnit;
    public Long alertConfigId;
    public Long alertGroupId;
    public String alertGroupName;
    public Boolean alertGroupEnabled;
    public Boolean enabled;
    public String createdAt;
    public String lastStatus;
    public Integer lastResponseTimeMs;
    public String lastMessage;
    public String lastCheckedAt;
}
