CREATE TABLE IF NOT EXISTS tuser (
    id DECIMAL(12,0) NOT NULL,
    userid VARCHAR(50) DEFAULT NULL,
    password VARCHAR(512) DEFAULT NULL,
    name VARCHAR(30) DEFAULT NULL,
    grade DECIMAL(12,0) DEFAULT NULL,
    lastlogin TIMESTAMP DEFAULT NULL,
    logins DECIMAL(12,0) DEFAULT NULL,
    chgpwdtime TIMESTAMP DEFAULT NULL,
    chgpwdlimit DECIMAL(12,0) DEFAULT NULL,
    status DECIMAL(12,0) DEFAULT NULL,
    iplimit VARCHAR(20) DEFAULT NULL,
    certno VARCHAR(60) DEFAULT NULL,
    orgid DECIMAL(10,0) DEFAULT NULL,
    photo BLOB,
    locktime TIMESTAMP DEFAULT NULL,
    retrycount INT DEFAULT NULL,
    lasttrytime TIMESTAMP DEFAULT NULL,
    userattribute INT DEFAULT NULL,
    PRIMARY KEY (id)
);

INSERT INTO tuser (
    id, userid, password, name, grade, lastlogin, logins, chgpwdtime, chgpwdlimit, status,
    iplimit, certno, orgid, photo, locktime, retrycount, lasttrytime, userattribute
)
SELECT 1, 'admin', '000000', 'admin', 1, NULL, 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM tuser WHERE id = 1);

CREATE TABLE IF NOT EXISTS login_audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(50) NOT NULL,
    user_name VARCHAR(30),
    action VARCHAR(20) NOT NULL,
    ip_address VARCHAR(64),
    event_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_login_audit_log_time
ON login_audit_log(event_time DESC);

CREATE TABLE IF NOT EXISTS monitor_service (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_name VARCHAR(255) NOT NULL,
    service_category VARCHAR(64) NOT NULL DEFAULT 'middleware',
    service_type VARCHAR(64) NOT NULL,
    cluster_name VARCHAR(255),
    monitor_reason VARCHAR(1000),
    endpoint VARCHAR(1024),
    host VARCHAR(255),
    port INT,
    check_mode VARCHAR(64) NOT NULL DEFAULT 'ping',
    check_command VARCHAR(100000),
    expected_result VARCHAR(100000),
    check_timeout_seconds DOUBLE,
    config_json VARCHAR(100000) NOT NULL DEFAULT '{}',
    secret_config_json VARCHAR(100000) NOT NULL DEFAULT '{}',
    check_interval INT DEFAULT 60,
    alert_config_id BIGINT,
    enabled INT DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS service_latest_status (
    service_id BIGINT PRIMARY KEY,
    status VARCHAR(32) NOT NULL,
    response_time_ms INT,
    message VARCHAR(100000),
    checked_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(service_id) REFERENCES monitor_service(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS monitor_check_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_id BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL,
    response_time_ms INT,
    message VARCHAR(100000),
    alert_type VARCHAR(64),
    checked_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    consumed INT DEFAULT 0,
    consumed_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(service_id) REFERENCES monitor_service(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS alert_policy (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_name VARCHAR(255) NOT NULL,
    trigger_type VARCHAR(64) NOT NULL,
    trigger_value VARCHAR(255),
    enabled INT DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS alert_channel (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_name VARCHAR(255) NOT NULL,
    channel_type VARCHAR(64) NOT NULL,
    config_json VARCHAR(100000),
    enabled INT DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS alert_group (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_name VARCHAR(255) NOT NULL,
    description VARCHAR(100000),
    enabled INT DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS group_policy_rel (
    group_id BIGINT NOT NULL,
    policy_id BIGINT NOT NULL,
    PRIMARY KEY (group_id, policy_id),
    FOREIGN KEY(group_id) REFERENCES alert_group(id) ON DELETE CASCADE,
    FOREIGN KEY(policy_id) REFERENCES alert_policy(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS group_channel_rel (
    group_id BIGINT NOT NULL,
    channel_id BIGINT NOT NULL,
    PRIMARY KEY (group_id, channel_id),
    FOREIGN KEY(group_id) REFERENCES alert_group(id) ON DELETE CASCADE,
    FOREIGN KEY(channel_id) REFERENCES alert_channel(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS service_alert_group (
    service_id BIGINT PRIMARY KEY,
    group_id BIGINT NOT NULL,
    FOREIGN KEY(service_id) REFERENCES monitor_service(id) ON DELETE CASCADE,
    FOREIGN KEY(group_id) REFERENCES alert_group(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS alert_state (
    service_id BIGINT NOT NULL,
    alert_key VARCHAR(128) NOT NULL,
    state VARCHAR(32) NOT NULL,
    fail_count INT DEFAULT 0,
    recover_count INT DEFAULT 0,
    active_policy_id BIGINT,
    active_trigger_type VARCHAR(64),
    last_status VARCHAR(32),
    last_message VARCHAR(100000),
    last_event_at TIMESTAMP,
    last_alert_at TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (service_id, alert_key),
    FOREIGN KEY(service_id) REFERENCES monitor_service(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS alert_notify_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_id BIGINT NOT NULL,
    alert_key VARCHAR(128) NOT NULL,
    alert_record_id BIGINT,
    alert_type VARCHAR(64),
    notify_status VARCHAR(32),
    notify_message VARCHAR(100000),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(service_id) REFERENCES monitor_service(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS host_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    host_name VARCHAR(255) NOT NULL,
    ip VARCHAR(255) NOT NULL,
    ssh_port INT DEFAULT 22,
    ssh_user VARCHAR(255),
    ssh_password_cipher VARCHAR(100000),
    private_key_cipher VARCHAR(100000),
    monitor_service_id BIGINT,
    cluster_name VARCHAR(255) DEFAULT 'Server Host',
    cpu_threshold_percent DOUBLE DEFAULT 85,
    memory_threshold_percent DOUBLE DEFAULT 85,
    disk_threshold_percent DOUBLE DEFAULT 85,
    cpu_alert_enabled INT DEFAULT 1,
    memory_alert_enabled INT DEFAULT 1,
    disk_alert_enabled INT DEFAULT 1,
    resource_alert_duration_enabled INT DEFAULT 1,
    resource_recover_duration_enabled INT DEFAULT 1,
    resource_alert_cooldown_enabled INT DEFAULT 1,
    resource_alert_duration_seconds INT DEFAULT 180,
    resource_recover_duration_seconds INT DEFAULT 180,
    resource_alert_cooldown_seconds INT DEFAULT 600,
    check_interval INT DEFAULT 60,
    enabled INT DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(monitor_service_id) REFERENCES monitor_service(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS host_process_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    host_id BIGINT NOT NULL,
    process_name VARCHAR(255) NOT NULL,
    match_keyword VARCHAR(100000) NOT NULL,
    check_command VARCHAR(100000),
    enabled INT DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(host_id) REFERENCES host_config(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS host_latest_metric (
    host_id BIGINT PRIMARY KEY,
    cpu_usage_percent DOUBLE,
    load_average DOUBLE,
    memory_used_percent DOUBLE,
    disk_used_percent DOUBLE,
    cpu_core_count INT,
    memory_total_mb DOUBLE,
    disk_mount_count INT,
    disk_metrics_json VARCHAR(100000),
    physical_disk_metrics_json VARCHAR(100000),
    checked_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(host_id) REFERENCES host_config(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS migration_marker (
    id VARCHAR(128) PRIMARY KEY,
    source_path VARCHAR(1024),
    backup_path VARCHAR(1024),
    config_rows BIGINT DEFAULT 0,
    rocksdb_rows BIGINT DEFAULT 0,
    completed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_monitor_service_type_enabled
ON monitor_service(service_type, enabled);

CREATE INDEX IF NOT EXISTS idx_monitor_service_category_enabled
ON monitor_service(service_category, enabled);

CREATE INDEX IF NOT EXISTS idx_service_latest_status_time
ON service_latest_status(checked_at DESC);

CREATE INDEX IF NOT EXISTS idx_monitor_check_event_service_time
ON monitor_check_event(service_id, checked_at DESC);

CREATE INDEX IF NOT EXISTS idx_monitor_check_event_consumed
ON monitor_check_event(consumed, id);

CREATE INDEX IF NOT EXISTS idx_service_alert_group_group
ON service_alert_group(group_id);

CREATE INDEX IF NOT EXISTS idx_alert_notify_record_service_time
ON alert_notify_record(service_id, created_at DESC);

MERGE INTO alert_policy KEY(id)
VALUES (1, 'DOWN consecutive 3 times', 'consecutive_down', '3', 1, CURRENT_TIMESTAMP);

MERGE INTO alert_policy KEY(id)
VALUES (2, 'Latency > 3 seconds', 'latency_gt_ms', '3000', 1, CURRENT_TIMESTAMP);

MERGE INTO alert_policy KEY(id)
VALUES (3, 'Service recovered', 'recovered', 'UP', 1, CURRENT_TIMESTAMP);
