package com.live.monitor.config;

import javax.annotation.PostConstruct;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

@Component
public class SchemaMigrationService {
    private final JdbcTemplate jdbcTemplate;

    public SchemaMigrationService(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    @PostConstruct
    public void migrate() {
        if (!tableExists("monitor_service")) {
            return;
        }
        createEventDrivenAlertTables();
        widenColumnIfPresent("tuser", "password", "VARCHAR(512)");
        addColumnIfMissing("monitor_service", "service_category", "VARCHAR(64) NOT NULL DEFAULT 'middleware'");
        addColumnIfMissing("monitor_service", "monitor_reason", "VARCHAR(1000)");
        addColumnIfMissing("monitor_service", "endpoint", "VARCHAR(1024)");
        addColumnIfMissing("monitor_service", "check_mode", "VARCHAR(64) NOT NULL DEFAULT 'ping'");
        addColumnIfMissing("monitor_service", "check_command", "VARCHAR(100000)");
        addColumnIfMissing("monitor_service", "expected_result", "VARCHAR(100000)");
        addColumnIfMissing("monitor_service", "config_json", "VARCHAR(100000) NOT NULL DEFAULT '{}'");
        addColumnIfMissing("monitor_service", "secret_config_json", "VARCHAR(100000) NOT NULL DEFAULT '{}'");
        addColumnIfMissing("host_process_config", "check_command", "VARCHAR(100000)");
        addColumnIfMissing("host_config", "monitor_service_id", "BIGINT");
        addColumnIfMissing("host_config", "cluster_name", "VARCHAR(255) DEFAULT 'Server Host'");
        addColumnIfMissing("host_config", "cpu_threshold_percent", "DOUBLE DEFAULT 85");
        addColumnIfMissing("host_config", "memory_threshold_percent", "DOUBLE DEFAULT 85");
        addColumnIfMissing("host_config", "disk_threshold_percent", "DOUBLE DEFAULT 85");
        addColumnIfMissing("host_config", "cpu_alert_enabled", "INT DEFAULT 1");
        addColumnIfMissing("host_config", "memory_alert_enabled", "INT DEFAULT 1");
        addColumnIfMissing("host_config", "disk_alert_enabled", "INT DEFAULT 1");
        addColumnIfMissing("host_config", "resource_alert_duration_seconds", "INT DEFAULT 180");
        addColumnIfMissing("host_config", "resource_recover_duration_seconds", "INT DEFAULT 180");
        addColumnIfMissing("host_config", "resource_alert_cooldown_seconds", "INT DEFAULT 600");
        addColumnIfMissing("host_config", "check_interval", "INT DEFAULT 60");
        addColumnIfMissing("host_latest_metric", "cpu_core_count", "INT");
        addColumnIfMissing("host_latest_metric", "memory_total_mb", "DOUBLE");
        addColumnIfMissing("host_latest_metric", "disk_mount_count", "INT");
        addColumnIfMissing("host_latest_metric", "disk_metrics_json", "VARCHAR(100000)");
        addColumnIfMissing("host_latest_metric", "physical_disk_metrics_json", "VARCHAR(100000)");
    }

    private void createEventDrivenAlertTables() {
        jdbcTemplate.execute("CREATE TABLE IF NOT EXISTS monitor_check_event (" +
            "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
            "service_id BIGINT NOT NULL, " +
            "status VARCHAR(32) NOT NULL, " +
            "response_time_ms INT, " +
            "message VARCHAR(100000), " +
            "alert_type VARCHAR(64), " +
            "checked_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, " +
            "consumed INT DEFAULT 0, " +
            "consumed_at TIMESTAMP, " +
            "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");
        jdbcTemplate.execute("CREATE TABLE IF NOT EXISTS alert_state (" +
            "service_id BIGINT NOT NULL, " +
            "alert_key VARCHAR(128) NOT NULL, " +
            "state VARCHAR(32) NOT NULL, " +
            "fail_count INT DEFAULT 0, " +
            "recover_count INT DEFAULT 0, " +
            "active_policy_id BIGINT, " +
            "active_trigger_type VARCHAR(64), " +
            "last_status VARCHAR(32), " +
            "last_message VARCHAR(100000), " +
            "last_event_at TIMESTAMP, " +
            "last_alert_at TIMESTAMP, " +
            "updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, " +
            "PRIMARY KEY (service_id, alert_key))");
        jdbcTemplate.execute("CREATE TABLE IF NOT EXISTS alert_notify_record (" +
            "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
            "service_id BIGINT NOT NULL, " +
            "alert_key VARCHAR(128) NOT NULL, " +
            "alert_record_id BIGINT, " +
            "alert_type VARCHAR(64), " +
            "notify_status VARCHAR(32), " +
            "notify_message VARCHAR(100000), " +
            "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");
        jdbcTemplate.execute("CREATE INDEX IF NOT EXISTS idx_monitor_check_event_service_time " +
            "ON monitor_check_event(service_id, checked_at DESC)");
        jdbcTemplate.execute("CREATE INDEX IF NOT EXISTS idx_monitor_check_event_consumed " +
            "ON monitor_check_event(consumed, id)");
        jdbcTemplate.execute("CREATE INDEX IF NOT EXISTS idx_alert_notify_record_service_time " +
            "ON alert_notify_record(service_id, created_at DESC)");
    }

    private boolean tableExists(String tableName) {
        Integer count = jdbcTemplate.queryForObject(
            "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = SCHEMA() AND table_name = ?",
            Integer.class,
            tableName.toLowerCase()
        );
        return count != null && count > 0;
    }

    private boolean columnExists(String tableName, String columnName) {
        Integer count = jdbcTemplate.queryForObject(
            "SELECT COUNT(*) FROM information_schema.columns " +
                "WHERE table_schema = SCHEMA() AND table_name = ? AND column_name = ?",
            Integer.class,
            tableName.toLowerCase(),
            columnName.toLowerCase()
        );
        return count != null && count > 0;
    }

    private void addColumnIfMissing(String tableName, String columnName, String definition) {
        if (tableExists(tableName) && !columnExists(tableName, columnName)) {
            jdbcTemplate.execute("ALTER TABLE " + tableName + " ADD COLUMN " + columnName + " " + definition);
        }
    }

    private void widenColumnIfPresent(String tableName, String columnName, String definition) {
        if (tableExists(tableName) && columnExists(tableName, columnName)) {
            jdbcTemplate.execute("ALTER TABLE " + tableName + " ALTER COLUMN " + columnName + " " + definition);
        }
    }
}
